name: Deploy Infra + Lambda to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build Lambda & Deploy Infra
    runs-on: ubuntu-latest

    env:
      AWS_REGION: sa-east-1
      LAMBDA_ZIP_PATH: lambda/lambda_function.zip
      S3_BUCKET_NAME: ${{ secrets.LAMBDA_BUCKET }}
      S3_KEY: lambda/lambda_function.zip

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependências da Lambda
        run: |
          cd lambda
          pip install -r requirements.txt -t .
          cd ..

      - name: Empacotar Lambda
        run: |
          zip -r $LAMBDA_ZIP_PATH lambda/lambda_function.py lambda/requirements.txt lambda/*.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Fazer upload do ZIP da Lambda pro S3
        run: |
          aws s3 cp $LAMBDA_ZIP_PATH s3://$S3_BUCKET_NAME/$S3_KEY

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
